caseSensitive: true
dictionaries:
  - en_US
  - companies
  - softwareTerms
  - misc
  - html
  - css
  - people
  - companies_custom
  - terminology
dictionaryDefinitions:
  - name: companies_custom
    path: cspell/companies_custom.txt
  - name: people
    path: cspell/people.txt
  - name: terminology
    path: cspell/terminology.txt
  - name: inclusive_language
    path: cspell/inclusive_language.txt
ignorePaths:
  - 'cspell/**'
  - pnpm-lock.yaml
  - '**/*.css'
  - '**/*.scss'
  - '**/*.snap'
  - '**/dist'
  - '**/node_modules'
  - '**/package.json'
  - '**/tsconfig.json'
  - www/src/pages/TR/** # ignore published specs
  - www/src/components/TokenPlayground/lib/examples/** # ignore external DSs
ignoreRegExpList:
  - <!--.*--> # ignore HTML comments
  - '@[A-Za-z0-9-_]+' # ignore social handles
